doctrine_migrations:
    migrations_paths:
        'Migrations\V1\Cards': '%kernel.project_dir%/migrations/v1_database_scheme/Cards'
        'Migrations\V1\Users': '%kernel.project_dir%/migrations/v1_database_scheme/Users'
    enable_profiler: false