controllersCard:
    resource:
        path: ../src/Example/Card/Infrastructure/Controller/
        namespace: App\FlashCards\Card\Infrastructure\Controller
    type: attribute
controllersUser:
    resource:
        path: ../src/Example/User/Infrastructure/Controller/
        namespace: App\FlashCards\User\Infrastructure\Controller
    type: attribute